---
# configure_systemd-resolved/tasks/main.yml

- name: 'Make sure {{ resolved_config_directory }}/ exists'
  ansible.builtin.file:
    path: '{{ resolved_config_directory }}/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Create {{ resolved_config_directory }}/ansible.conf'
  ansible.builtin.template:
    src: 'resolved.conf.j2'
    dest: '{{ resolved_config_directory }}/ansible.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the systemd-resolved service'
